#!/usr/bin/env bash
# View/Clip — one-command migration export
# Produces a self-contained bundle: code + env + mongodump + manifest + checklist.
# Re-runnable. Never mutates source data.
#
# Usage:  bash scripts/export_for_migration.sh [output_dir]
#         Default output_dir = ./viewclip-export-<YYYY-MM-DD>

set -euo pipefail

OUT="${1:-./viewclip-export-$(date +%F)}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== View/Clip migration export ==="
echo "Source:  $ROOT"
echo "Target:  $OUT"
echo

mkdir -p "$OUT"/{code,env,mongo}

# ---------------------------------------------------------------------
# 1. Code snapshot (excludes runtime / caches / credentials)
# ---------------------------------------------------------------------
echo "→ copying code…"
rsync -a --delete \
  --exclude '.git' \
  --exclude 'node_modules' \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  --exclude 'build' \
  --exclude 'dist' \
  --exclude '.emergent' \
  --exclude 'test_reports' \
  --exclude '*.log' \
  --exclude 'backend/.env' \
  --exclude 'frontend/.env' \
  "$ROOT"/ "$OUT/code"/

# ---------------------------------------------------------------------
# 2. Env files (copied RAW — guard carefully)
# ---------------------------------------------------------------------
echo "→ copying .env files…"
[ -f "$ROOT/backend/.env" ]  && cp "$ROOT/backend/.env"  "$OUT/env/backend.env"  || echo "  (skipped: no backend/.env)"
[ -f "$ROOT/frontend/.env" ] && cp "$ROOT/frontend/.env" "$OUT/env/frontend.env" || echo "  (skipped: no frontend/.env)"
chmod 600 "$OUT/env"/*.env 2>/dev/null || true

# ---------------------------------------------------------------------
# 3. MongoDB dump (every DB on the current MONGO_URL)
# ---------------------------------------------------------------------
if command -v mongodump >/dev/null 2>&1; then
  MONGO_URL="$(grep -E '^MONGO_URL=' "$ROOT/backend/.env" 2>/dev/null | cut -d= -f2- | tr -d '"' | tr -d "'")"
  MONGO_URL="${MONGO_URL:-mongodb://localhost:27017}"
  echo "→ mongodump from $MONGO_URL …"
  mongodump --uri="$MONGO_URL" --out="$OUT/mongo/mongodump" --quiet || {
    echo "  mongodump failed — continuing without DB snapshot."
  }
else
  echo "→ mongodump not installed — skipping DB dump."
  echo "  Install mongodb-database-tools and re-run, or dump manually."
fi

cat > "$OUT/mongo/restore.sh" <<'EOF'
#!/usr/bin/env bash
# Restore this dump into any Mongo instance.
# Usage:  bash restore.sh "mongodb+srv://user:pass@cluster.mongodb.net/"
set -euo pipefail
TARGET="${1:-mongodb://localhost:27017}"
mongorestore --uri="$TARGET" "$(dirname "$0")/mongodump"
echo "Done. Verify collection counts match MANIFEST.json."
EOF
chmod +x "$OUT/mongo/restore.sh"

# ---------------------------------------------------------------------
# 4. Manifest — counts per collection + git SHA + timestamp
# ---------------------------------------------------------------------
echo "→ building MANIFEST.json…"
GIT_SHA="$(cd "$ROOT" && git rev-parse HEAD 2>/dev/null || echo 'no-git')"
APP_VERSION="$(grep -E '^APP_VERSION' "$ROOT/backend/.env" 2>/dev/null | cut -d= -f2 | tr -d '"' || echo 'unknown')"

COUNTS="{}"
if command -v mongosh >/dev/null 2>&1; then
  COUNTS="$(mongosh --quiet "${MONGO_URL:-mongodb://localhost:27017}" --eval '
    const out = {};
    db.getMongo().getDBNames().filter(n => n.startsWith("viewclip") || n === "streaming_platform").forEach(n => {
      out[n] = {};
      db.getSiblingDB(n).getCollectionNames().forEach(c => out[n][c] = db.getSiblingDB(n)[c].countDocuments({}));
    });
    JSON.stringify(out);
  ' 2>/dev/null || echo '{}')"
fi

cat > "$OUT/MANIFEST.json" <<JSON
{
  "exported_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "source_host": "$(hostname)",
  "app_version": "$APP_VERSION",
  "git_sha": "$GIT_SHA",
  "collection_counts": $COUNTS
}
JSON

# ---------------------------------------------------------------------
# 5. Checklist
# ---------------------------------------------------------------------
cat > "$OUT/CHECKLIST.md" <<'EOF'
# View/Clip Migration Checklist

> Generated by `scripts/export_for_migration.sh`.
> Read `MIGRATION.md` (in `code/`) for full context.

## Before you leave Emergent
- [ ] Verify `env/backend.env` and `env/frontend.env` are NON-empty
- [ ] Verify `mongo/mongodump/` contains folders for `viewclip_identity`, `viewclip_streaming`, `viewclip_vault`
- [ ] Copy `MANIFEST.json` — remember the collection counts; you'll validate against them after restore
- [ ] Record the current `VAULT_ENCRYPTION_KEY` — without it you CANNOT decrypt banking info or admin TOTP secrets

## On the new host
- [ ] Create target Mongo (Atlas / DocDB / self-hosted) — see `MIGRATION.md` §3
- [ ] `bash mongo/restore.sh "<target-mongo-uri>"` — wait for completion
- [ ] Place `env/backend.env` at `<new-repo>/backend/.env` and update:
      - `MONGO_URL` → new target
      - `CORS_ORIGINS` → your frontend domain
      - `JWT_SECRET` → optional: rotate (invalidates old sessions)
- [ ] Place `env/frontend.env` at `<new-repo>/frontend/.env` and update:
      - `REACT_APP_BACKEND_URL` → your backend URL
      - Remove Emergent-only flags (`REACT_APP_ENABLE_VISUAL_EDITS`, `ENABLE_HEALTH_CHECK`)

## Smoke tests
- [ ] `curl <backend>/api/health` → `{"status":"ok","version":"1.4.0"}`
- [ ] `curl <backend>/api/ready` → `{"status":"ready"}`
- [ ] Log in at `<frontend>/admin/login` with your existing admin creds
- [ ] Admin → System tab → confirm 3 DB layers OK, version matches
- [ ] Verify any pre-migration user can log in (JWT_SECRET not rotated)
- [ ] Verify banking info still decrypts (VAULT_ENCRYPTION_KEY correct)

## Clean up
- [ ] Keep the Emergent pod hot for 48h as rollback safety net
- [ ] After 48h of green metrics, delete pod and rotate all exported credentials
EOF

# ---------------------------------------------------------------------
echo
echo "✓ Export ready at: $OUT"
echo "  Next step: open $OUT/CHECKLIST.md"
